"""Tuple is Immutable
Allows duplicate values
Faster than lists
Use a tuple when you need to store data that should not be changed, or when you need to store duplicate values."""

x=("HTML","CSS","JavaScript","Python") #This is a tuple in Python. A tuple is a collection of items that are ordered and unchangeable. The items in a tuple are enclosed in parentheses () and separated by commas. In this case, the tuple x contains four string values: "HTML", "CSS", "JavaScript", and "Python". Tuples can hold different data types, including strings, integers, floats, and even other tuples. The variable name x is assigned to this tuple, and it can be used to access the items in the tuple.
sir=("Subhradip","Soumya","Sourav") #This is a tuple in Python. A tuple is a collection of items that are ordered and unchangeable. The items in a tuple are enclosed in parentheses () and separated by commas. In this case, the tuple sir contains three string values: "Subhradip", "Soumya", and "Sourav". Tuples can hold different data types, including strings, integers, floats, and even other tuples. The variable name sir is assigned to this tuple, and it can be used to access the items in the tuple. 
mix=x+sir #The above line concatenates the two tuples x and sir to create a new tuple mix. In Python, the plus (+) operator is used to concatenate tuples. The resulting tuple mix contains all the items from both tuples, in the order they were concatenated. The variable name mix is assigned to this new tuple, and it can be used to access the items in the tuple.
print(mix) #Print the entire tuple mix, which contains the items from both tuples x and sir. The print function is used to display output in Python. The entire tuple is printed as it is, enclosed in parentheses () and separated by commas.  
print(x[1]) #The above line prints the second item in the tuple x, which is "CSS". In Python, tuples are zero-indexed, meaning that the first item in the tuple has an index of 0, the second item has an index of 1, and so on. The square brackets [] are used to access items in a tuple by their index
print(x[-1]) #The above line prints the last item in the tuple x, which is "Python". In Python, negative indexing can be used to access items in a tuple from the end. The index -1 refers to the last item, -2 refers to the second-to-last item, and so on. The square brackets [] are used to access items in a tuple by their index.    
print(x) #Print the entire tuple x, which contains the items: "HTML", "CSS", "JavaScript", and "Python". The print function is used to display output in Python. The entire tuple is printed as it is, enclosed in parentheses () and separated by commas.  
